server:
  port: 8080 # 后端运行端口

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL:jdbc:mysql://localhost:3306/emall_db?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:}

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  mail:
    host: ${MAIL_HOST:smtp.qq.com}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

  cache:
    type: redis
    cache-names:
      - productList
      - categoryList
      - hotSearches
    redis:
      time-to-live: 3600000
      cache-null-values: true

mybatis-plus:
  configuration:
    # 开启 SQL 日志输出，我们在 IDEA 控制台就能看到它执行了什么 SQL，排错神器
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto # 告诉 MyBatis-Plus 我们的主键是自增的
